; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Thu Nov 18 2021 22:17:45 GMT+0000 (UTC)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


