; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Thu Nov 18 2021 22:17:45 GMT+0000 (UTC)
G91             ; relative positioning
G1 H1 Z47 F600 ; move Z up until the endstop is triggered
G1 Z-0.5
G1 H1 Z47 F200
G92 Z42         ; set Z position to axis maximum (you may want to adjust this)