; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Thu Nov 18 2021 22:17:45 GMT+0000 (UTC)
G53 G0 Z42       ; Move Z to top (using machine coordinates)
G91              ; relative positioning
G1 H1 Y905 F4800 ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y-2 F6000  ; go back a few mm
G1 H1 Y905 F360  ; move slowly to Y axis endstop once more (second pass)
G90              ; absolute positioning

