; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Thu Nov 18 2021 22:17:45 GMT+0000 (UTC)
G91  		   ; relative positioning
M913 Z66       ; reduce motor current
G1 H1 Z47 F360 ; move Z up until the endstop is triggered
G92 Z42        ; set Z position to axis maximum (you may want to adjust this)
M913 Z100      ; set motor current to 100%
